### ISSUE TITLE
论文原文放出来了吗，很想拜读一下，期待

### ISSUE THREAD

**Issue by wusj18** [ramonzhan/SAMA#1]
有幸在AIS听了论文的分享，很想拜读一下原文，请问有链接吗。另外不知道能否提供数据集的其他格式比如json，csv，txt这些。非常感谢！！！

**Comment by ramonzhan** [comment]
不好意思一直没有看到，会议已经开了，论文应该也已经放出来了。数据集的话由于是自己在猎聘上爬的，所以就按自己的喜好处理成了pickle，暂时还没有其他格式。:)
